language: go
dist: trusty

git:
  depth: 11

go: 1.x

addons:
  sonarcloud:
    organization: tynn-github

script:
  - go test -coverprofile=coverage.out
  - "
    sonar-scanner
      -Dsonar.projectKey=sonar-badge-proxy
      -Dsonar.sources=.
      -Dsonar.tests=.
      -Dsonar.test.inclusions='**/*_test.go'
      -Dsonar.go.coverage.reportPaths=coverage.out
    "
